// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PotatoBot.Models;

namespace PotatoBot.Migrations
{
    [DbContext(typeof(GuildContext))]
    [Migration("20200501174032_MutedUsersTable")]
    partial class MutedUsersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "5.0.0-preview.3.20181.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DAL.Models.MutedUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("MutedUsers");
                });

            modelBuilder.Entity("PotatoBot.Models.GuildData", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal[]>("AutoRolesOnJoin")
                        .HasColumnType("numeric[]");

                    b.Property<bool>("EnableMessageLogs")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableModLogs")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableWelcomeMessages")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveMessage")
                        .HasColumnType("text");

                    b.Property<List<GuildLog>>("Logs")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("MessageLogsChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModLogsChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MutedRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("text");

                    b.Property<decimal>("WelcomeMessagesChannel")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
